LibraryManagementSystem/LibraryManagementSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^bookSearch/', include('bookSearch.urls')),
	url(r'^$', include('bookSearch.urls')),
	url(r'^borrowers/', include('borrowers.urls')),
    url(r'^bookLoans/', include('bookLoans.urls')),
	url(r'^admin/', admin.site.urls),
]

LibraryManagementSystem/bookLoans/urls.py
from django.conf.urls import url

from . import views
app_name = 'bookLoans'
urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^checkOut$', views.checkOut, name='checkOut'),
	url(r'^checkIn$', views.checkIn, name='checkIn'),
	url(r'^bookCheckIn$', views.bookCheckIn, name='bookCheckIn'),
	url(r'^fines$', views.fines, name='fines'),
	url(r'^finesUpdate$', views.finesUpdate, name='finesUpdate'),
	url(r'^payFine$', views.payFine, name='payFine'),
]

LibraryManagementSystem/bookLoans/models.py
from __future__ import unicode_literals
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _

from django.db import models

# Create your models here.

class BookLoan(models.Model):
	loan_id = models.AutoField(primary_key=True, db_column="loan_id")
	book = models.ForeignKey('bookSearch.Book', on_delete = models.CASCADE, db_column="isbn", related_name = "loaners")
	borrower = models.ForeignKey('borrowers.Borrower', on_delete = models.CASCADE, db_column="card_id", related_name = "loans")
	date_out = models.DateField(db_column="date_out")
	due_date = models.DateField(db_column="due_date")
	date_in = models.DateField(db_column="date_in", null = True, blank = True)

	def clean(self, *args, **kwargs):
		if (self.due_date < self.date_out):
			raise ValidationError({'due_date': _("Due date must be date greater than Check Out date.")})
		if (self.date_in is not None and self.date_in < self.date_out):
			raise ValidationError({'date_in': _("Check in cannot happen before check out.")})
		else :
			if (self.date_in is None and BookLoan.objects.all().filter(book__exact = self.book_id).filter(date_in__isnull = True).exists()):
				raise ValidationError({'book': _("This book has been already checked out.")})
		if (self.date_in is None and self.borrower_id is not None and self.borrower_id != ""):
			if (BookLoan.objects.all().filter(borrower__exact = self.borrower_id).filter(date_in__isnull = True).count() > 2):
				raise ValidationError({'borrower': _("This borrower already has 3 books loaned.")})
		super(BookLoan, self).clean(*args, **kwargs)

	class Meta:
		db_table = "book_loans"

class Fine(models.Model):
	loan = models.OneToOneField("BookLoan", primary_key=True, on_delete = models.CASCADE, db_column="loan_id", related_name = "fines")
	fine_amt = models.DecimalField(db_column="fine_amt", max_digits=6, decimal_places = 2)
	paid = models.BooleanField(db_column="paid", default=False)

	class Meta:
		db_table = "fines"

LibraryManagementSystem/bookLoans/views.py
import datetime
from string import rsplit
from django.shortcuts import render, redirect
from django.core.exceptions import ValidationError
from django.db.models import Q, Sum, Count
from django.http import HttpResponseNotFound
from django.contrib import messages
from .models import BookLoan, Fine
from borrowers.models import Borrower
from django.http import JsonResponse
from django.db import connection
import sys

def home(request):
	context = {}
	return render(request, 'bookLoans/home.html', context)

def checkOut(request):
	book_loan = BookLoan()
	form_errors = None
	model_is_clean = True
	loan_id = None
	if (request.method == 'POST'):
		if 'book' in request.POST and 'borrower' in request.POST:
			book_loan.book_id = request.POST['book']
			book_loan.borrower_id = request.POST['borrower']
			book_loan.date_out = datetime.date.today()
			book_loan.due_date = book_loan.date_out + datetime.timedelta(days=14)
			book_loan.date_in = None
			try:
				book_loan.full_clean()
			except ValidationError as e:
				form_errors = e.message_dict
				model_is_clean = False
			if (model_is_clean):
				book_loan.save()
				loan_id = book_loan.loan_id
				book_loan = BookLoan()
			else :
				book_loan.book_id = request.POST['book'] if 'book' in request.POST else ""
				book_loan.borrower_id = request.POST['borrower'] if 'borrower' in request.POST else ""
	context = {'book_loan' : book_loan, 'form_errors' : form_errors, 'loan_id' : loan_id}
	return render(request, 'bookLoans/check_out.html', context)

def checkIn(request):
	book_id = None if ('book' not in request.GET) else request.GET['book']
	borrower_id = None if ('borrower_id' not in request.GET) else request.GET['borrower_id']
	borrower_name = None if ('borrower_name' not in request.GET) else request.GET['borrower_name']
	page_num = int(request.GET['page']) if 'page' in request.GET and request.GET['page'].isdigit() else 0
	book_loans = None
	nxt_params = None
	back_params = None
	if (any(x is not None for x in [book_id, borrower_id, borrower_name])):
		book_loans = BookLoan.objects.all().select_related('borrower').prefetch_related('borrower')
		book_loans = book_loans.filter(date_in__isnull = True)
		if book_id is not None and book_id != '':
			book_loans = book_loans.filter(book_id__exact = book_id)
		else:
			book_id = ''
		if borrower_id is not None and borrower_id != '':
			book_loans = book_loans.filter(borrower_id__exact = borrower_id)
		else:
			borrower_id = ''
		if borrower_name is not None and borrower_name != '':
			names = borrower_name.rsplit(" ", 1)
			if (len(names) > 1):
				book_loans = book_loans.filter(borrower__first_name__icontains = names[0])
				book_loans = book_loans.filter(borrower__last_name__icontains = names[1])
			else :
				book_loans = book_loans.filter(Q(borrower__first_name__icontains = names[0]) | Q(borrower__last_name__icontains = names[0]))
		else:
			borrower_name = ''
		book_loans = book_loans[(page_num * 10):(page_num * 10)+11]
		nxt_params = "?book="+book_id+"&borrower_id="+borrower_id+"&borrower_name="+borrower_name+("&page=%d") % (page_num + 1)
		back_params = "?book="+book_id+"&borrower_id="+borrower_id+"&borrower_name="+borrower_name+("&page=%d") % (page_num - 1)
	context = {'book_loans' : book_loans, 'book_id' : book_id, 'borrower_id' : borrower_id, 'borrower_name' : borrower_name, 'nxt_params' : nxt_params, 'back_params' : back_params, 'page_num':page_num}
	return render(request, 'bookLoans/check_in.html', context)

def bookCheckIn(request):
	if request.method != 'POST' or 'loan_id' not in request.POST:
		return HttpResponseNotFound('Invalid Request')
	try:
		book_loan = BookLoan.objects.get(loan_id = request.POST['loan_id'])
		if book_loan.date_in is None:
			book_loan.date_in = datetime.date.today()
			book_loan.full_clean()
			book_loan.save()
			messages.success(request, 'The book has been checked in successfully.')
		else:
			messages.error(request, 'This book has already been checked in.')
	except ValidationError as e:
		for key, errors in e.message_dict.items():
			for error in errors:
				messages.error(request, errors)
	except:
		messages.error(request, 'Book Loan not found. Please check again.')
	return redirect('bookLoans:checkIn')

def fines(request):
	page_num = int(request.GET['page']) if 'page' in request.GET and request.GET['page'].isdigit() else 0
	borrower_id = request.GET['borrower'] if 'borrower' in request.GET else ''
	select_string = "borrowers.first_name, borrowers.last_name, borrowers.borrower_id, SUM(fines.fine_amt) AS total_fine"
	from_string = "fines INNER JOIN book_loans ON fines.loan_id = book_loans.loan_id INNER JOIN borrowers ON borrowers.borrower_id = book_loans.card_id"
	where_string = "TRUE"
	group_by_string = "borrowers.borrower_id"
	order_by_string = "total_fine DESC"
	limit_string = "11"
	offset_string = "%s" % (page_num * 10)
	should_filter = 'filter' in request.GET and request.GET['filter'].isdigit() and int(request.GET['filter']) > 0
	sql_params = {}
	if should_filter:
		where_string += " AND fines.paid = FALSE"
	if borrower_id != '':
		where_string += " AND borrowers.borrower_id = %(borrower_id)s"
		sql_params['borrower_id'] = borrower_id
	sql = "SELECT " + select_string + " FROM " + from_string + " WHERE " + where_string + " GROUP BY " + group_by_string + " ORDER BY " + order_by_string + " LIMIT " + limit_string + " OFFSET " + offset_string
	borrowers = Borrower.objects.raw(sql, sql_params)
	borrowers = list(borrowers)
	context = {'borrowers' : borrowers, 'page_num' : page_num, 'should_filter' : should_filter, 'borrower_id' : borrower_id}
	return render(request, 'bookLoans/fines.html', context)

def finesUpdate(request):
	if (request.is_ajax) :
		loan_ids = []
		with connection.cursor() as cursor:
			update_1 = "UPDATE fines SET fine_amt = (DATE_PART('day', age(book_loans.date_in, book_loans.due_date)) * 0.25) FROM book_loans WHERE fines.loan_id = book_loans.loan_id AND book_loans.date_in IS NOT NULL AND fines.paid = FALSE AND book_loans.date_in > book_loans.due_date"
			cursor.execute(update_1)
			update_2 = "UPDATE fines SET fine_amt = (DATE_PART('day', age(current_date, book_loans.due_date)) * 0.25) FROM book_loans WHERE fines.loan_id = book_loans.loan_id AND book_loans.date_in IS NULL AND fines.paid = FALSE AND current_date > book_loans.due_date"
			cursor.execute(update_2)
			sql = "SELECT book_loans.loan_id, book_loans.due_date, book_loans.date_in FROM book_loans LEFT JOIN fines ON book_loans.loan_id = fines.loan_id WHERE fines.loan_id IS NULL AND current_date > book_loans.due_date AND (book_loans.date_in IS NULL OR book_loans.date_in > book_loans.due_date)"
			cursor.execute(sql)
			loan_ids = cursor.fetchall()

		current_date = datetime.date.today()
		for loan_id in loan_ids:
			fine = Fine()
			fine.loan_id = loan_id[0]
			due_date = loan_id[1]
			date_in = loan_id[2]
			fine.paid = False
			if date_in is None:
				fine.fine_amt = (current_date - due_date).days * 0.25
			else:
				fine.fine_amt = (date_in - due_date).days * 0.25
			try:
				fine.full_clean()
				fine.save()
			except Exception as e:
				pass
		messages.success(request, 'Fines are refreshed successfully!')
		data = {'status' : 'SUCCESS'}
		return JsonResponse(data)
	else:
		return HttpResponseNotFound("You are not allowed to request this url.")

def payFine(request):
	if request.method != 'POST' or 'card_id' not in request.POST or not request.POST['card_id'].isdigit():
		return HttpResponseNotFound('Invalid Request')
	try:
		fines = Fine.objects.all().filter(loan__borrower_id = int(request.POST['card_id'])).filter(paid=False).filter(loan__date_in__isnull = False)
		results = fines.aggregate(tot_fine = Sum('fine_amt'), num_fine = Count('loan_id'))
		fines.update(paid=True)
		if(results['num_fine'] > 0):
			messages.success(request, 'Payment of $%s has been recorded on the card number %s for total of %s fines.' % (results['tot_fine'], request.POST['card_id'], results['num_fine']))
		else:
			messages.error(request, "No valid payments to record")
	except:
		messages.error(request, 'Invalid card id provided!')
	return redirect('bookLoans:fines')

LibraryManagementSystem/bookLoans/templates/bookLoans/check_in.html
{% extends "layout_1.html" %}
{% block title %}Book Loans{% endblock %}
{% block nav_book_loans %}active{% endblock %}
{% block content %}
<div class="col-md-8 col-md-offset-2" align="center">
	<form method="GET" action="{% url 'bookLoans:checkIn' %}">
		{% csrf_token %}
		<table class="check_out_form">
			<tr>
				<td>Card ID</td>
				<td><input pattern="[0-9]*" name="borrower_id" value="{{borrower_id|default_if_none:''}}" title="Card number must be a valid number." /></td>
			</tr>
			<tr>
				<td>Borrower Name</td>
				<td><input type="text" name="borrower_name" value="{{borrower_name|default_if_none:''}}"/></td>
			</tr>
			<tr>
				<td>Book ISBN</td>
				<td><input pattern=".{10}" name="book" value="{{book_id|default_if_none:''}}" title="ISBN must be of length 10." /></td>
			</tr>
			<tr>
				<td colspan="2">
					<div align="center">
						<input type="reset" name="reset" class="btn btn-default mr10" />
						<input type="submit" name="submit" value="Submit" class="btn btn-success ml10" />
					</div>
				</td>
			</tr>
		</table>
	</form>
	{% if book_loans is not None %}
		<div>
			<table class="book_search_results" style="width: 100%">
				<tr>
					<th>ISBN</th>
					<th>Card ID</th>
					<th>Borrower Name</th>
					<th>Check IN</th>
				</tr>
				{% for book_loan in book_loans %}
					{% if forloop.first %}
						<form id="check_in_form" method="POST" action="{% url 'bookLoans:bookCheckIn' %}">
							{% csrf_token %}<input type="hidden" name="loan_id" id="check_in" />
						</form>
					{% endif %}
					{% if not forloop.last or book_loans|length < 11 %}
						<tr>
							<td>{{ book_loan.book_id }}</td>
							<td>{{ book_loan.borrower_id }}</td>
							<td>{{ book_loan.borrower.first_name }} {{book_loan.borrower.last_name}}</td>
							<td><div class="check_in_button btn btn-default" loan_id='{{book_loan.loan_id}}'>Check In</div></td>
						</tr>
					{% endif %}
				{% empty %}
					<tr>
						<td colspan="4">Sorry, no results were found with those combinations.</td>
					</tr>
				{% endfor %}
			</table>
			{% if book_loans|length == 11%}
				<a href="{% url 'bookLoans:checkIn' %}{{nxt_params}}" class="fr">Next</a>
			{% endif %}
			{% if page_num > 0 %}
				<a href="{% url 'bookLoans:checkIn' %}{{back_params}}" class="fl">Back</a>
			{% endif %}
		</div>
	{% endif %}
</div>
{% endblock %}
{% block script %}
{% if book_loans is not None and book_loans|length > 0%}
	<script type="text/javascript">
		$(function() {
			$('.check_in_button').click(function() {
				$('#check_in').val($(this).attr('loan_id'));
				$('#check_in_form').submit();
			});
		});
	</script>
{% endif %}
{% endblock %}

LibraryManagementSystem/bookLoans/templates/bookLoans/check_out.html
{% extends "layout_1.html" %}
{% block title %}Book Loans{% endblock %}
{% block nav_book_loans %}active{% endblock %}
{% block content %}
<div class="col-md-8 col-md-offset-2" align="center">
	{% if loan_id is not None %}
		<div class="col-md-8 col-md-offset-2 alert alert-success">
			The book has been successfully checked out
		</div>
		<br/>
		<br/>
		<br/>
		<br/>
	{% endif %}
	{% if form_errors is not None %}
		<div class="col-md-8 col-md-offset-2 alert alert-danger">
			Following errors have been detected:
			<ul>
				{% for key, errors in form_errors.items %}
					{% for error in errors %}
						<li>{{key}}: {{error | stringformat:"s"}}</li>
					{% endfor %}
				{% endfor %}
			</ul>
		</div>
	{% endif %}
	<form method="POST" action="{% url 'bookLoans:checkOut' %}">
	{% csrf_token %}
		<table class="check_out_form">
			<tr>
				<td>Card ID</td>
				<td><input pattern="[0-9]*" name="borrower" value="{{book_loan.borrower_id|default_if_none:''}}" title="Card number must be a valid number." /></td>
			</tr>
			<tr>
				<td>Book ISBN</td>
				<td><input pattern=".{10}" name="book" value="{{book_loan.book_id|default_if_none:''}}" title="ISBN must be of length 10." /></td>
			</tr>
			<tr>
				<td colspan="2">
					<div align="center">
						<input type="reset" name="reset" class="btn btn-default mr10" />
						<input type="submit" name="submit" value="Submit" class="btn btn-success ml10" />
					</div>
				</td>
			</tr>
		</table>
	</form>
</div>
{% endblock %}

LibraryManagementSystem/bookLoans/templates/bookLoans/fines.html
{% extends "layout_1.html" %}
{% load staticfiles %}
{% block title %}Book Loans{% endblock %}
{% block nav_book_loans %}active{% endblock %}
{% block content %}
<div class="col-md-8 col-md-offset-2" align="center">
	<div>
		<a class="btn btn-info" href="{% url 'bookLoans:fines' %}?filter={% if should_filter %}0{% else %}1{% endif %}">{% if should_filter %}Include Paid Fines{% else %}Remove Paid Fines{% endif %}</a>
		<div style="display: inline-block;">
			<div class="btn btn-default" id="refresh_fines">Refresh Fines</div><img class="ajax-loader" src="{% static 'images/ajax-loader.gif' %}" style="display: none;" />
		</div>
	</div>
	<div>
		<form method="GET" action="{% url 'bookLoans:fines' %}">
			{% csrf_token %}
			<table class="check_out_form">
				<tr>
					<td>Card ID</td>
					<td><input pattern="[0-9]+" name="borrower" value="{{borrower_id|default_if_none:''}}" title="Card number must be a valid number." /></td>
				</tr>
				<tr>
					<td colspan="2">
						<div align="center">
							<input type="reset" name="reset" class="btn btn-default mr10" />
							<input type="submit" name="submit" value="Submit" class="btn btn-success ml10" />
						</div>
					</td>
				</tr>
			</table>
		</form>
	</div>
	<div>
		<table class="book_search_results" style="width: 100%">
			<tr>
				<th>Borrower Name</th>
				<th>Card ID</th>
				<th>Total Fine</th>
				<th>Record Fine Payment</th>
			</tr>
			{% for borrower in borrowers %}
				{% if forloop.first %}
					<form id="pay_fine_form" method="POST" action="{% url 'bookLoans:payFine' %}">
						{% csrf_token %}
						<input type="hidden" name="card_id" id="pay_fine_card" />
					</form>
				{% endif %}
				{% if not forloop.last or borrowers|length < 11 %}
					<tr>
						<td>{{ borrower.first_name }} {{borrower.last_name }}</td>
						<td>{{ borrower.borrower_id }}</td>
						<td>{{ borrower.total_fine}}</td>
						<td><div class="record_fine_button btn btn-info" card_id='{{borrower.borrower_id}}'>Record</div></td>
					</tr>
				{% endif %}
			{% empty %}
				<tr>
					<td colspan="3">No fines yet!</td>
				</tr>
			{% endfor %}
		</table>
		{% if borrowers|length == 11%}
			<a href="{% url 'bookLoans:fines' %}?page={{page_num | add:'1'}}" class="fr">Next</a>
		{% endif %}
		{% if page_num > 0 %}
			<a href="{% url 'bookLoans:fines' %}?page={{page_num | add:'-1'}}" class="fr">Back</a>
		{% endif %}
	</div>
</div>
{% endblock %}
{% block script %}
<script type="text/javascript">
	$(function() {
		$('#refresh_fines').click(function() {
			$(this).addClass('submitted');
			$(this).hide();
			$(this).siblings('.ajax-loader').show()
			$.get("{% url 'bookLoans:finesUpdate' %}", function() {
				window.location.replace("{% url 'bookLoans:fines' %}");
			});
		});
		{% if borrowers|length > 0 %}
			console.log("Rendered");
			$('.record_fine_button').click(function() {
				$('#pay_fine_card').val($(this).attr('card_id'));
				$('#pay_fine_form').submit();
			});
		{% endif %}
	});
</script>
{% endblock%}

LibraryManagementSystem/bookLoans/templates/bookLoans/home.html
{% extends "layout_1.html" %}
{% block title %}Book Loans{% endblock %}
{% block nav_book_loans %}active{% endblock %}
{% block content %}
<div class="col-md-8 col-md-offset-2" align="center">
	You can check in, check out books, manage the fines of the borrowers in this section.
	<br/><br/>
	<a href="{% url 'bookLoans:checkOut' %}" class="btn btn-primary">Check Out</a>
	<br/><br/>
	<a href="{% url 'bookLoans:checkIn' %}" class="btn btn-primary">Check In</a>
	<br/><br/>
	<a href="{% url 'bookLoans:fines' %}" class="btn btn-primary">Fines</a>
</div>
{% endblock %}